[pytest]
asyncio_mode=auto

pythonpath = . custom_components
# Verbose logging is disabled by default. Enable log_cli=true ONLY for single-test debugging.
log_cli = false
log_cli_level = DEBUG
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S