# https://www.home-assistant.io/integrations/default_config/
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: 8123

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.price_tracker: debug
    custom_components.price_tracker_response: info
    custom_components.price_tracker_response_ssg: info
    custom_components.price_tracker_response_smartstore: info
    custom_components.price_tracker_response_coupang: info
    custom_components.price_tracker_response_ncnc: debug
    custom_components.price_tracker_response_rankingdak: info

