update_entity:
  name: Update Entity
  description: Manually triggers an update for a price tracker entity.
  fields:
    entity_id:
      name: Entity ID
  description: The entity_id of the price tracker sensor to update. Specify 'ALL' (case-insensitive) to update all price_buywisely sensors.
      required: true
      # selector:
      #   entity:
      #     domain: sensor